name: UI Docker Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'serving_pipeline/ui.py'
      - 'serving_pipeline/Dockerfile.ui'
      - 'serving_pipeline/requirements.txt'
      - 'serving_pipeline/sample_retrieval.py'
      - '.github/workflows/ui-build.yml'
  pull_request:
    paths:
      - 'serving_pipeline/ui.py'
      - 'serving_pipeline/Dockerfile.ui'
      - 'serving_pipeline/requirements.txt'
      - 'serving_pipeline/sample_retrieval.py'
      - '.github/workflows/ui-build.yml'

env:
  REGISTRY: ghcr.io
  REF_REPO: thuannan/aio2025-mlops-project01
  DOCKER_BUILDKIT: 1
  SERVING_REPO_PATH: /home/mlops/Repository/aio2025-mlops-project01/serving_pipeline
  API_BASE_URL: http://api.mlopsvn.space

jobs:
  ui:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker UI
        id: meta-ui
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REF_REPO }}-ui
          tags: |
            # Tag for main branch
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # Tag with commit SHA
            type=sha,prefix={{branch}}-

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push UI Docker image
        id: push-ui
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.SERVING_REPO_PATH }}
          file: ${{ env.SERVING_REPO_PATH }}/Dockerfile.ui
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta-ui.outputs.tags }}
          labels: ${{ steps.meta-ui.outputs.labels }}
          build-args: |
            API_BASE_URL=${{ env.API_BASE_URL }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REF_REPO }}-ui:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REF_REPO }}-ui:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.push-ui.outputs.digest }}
